Replace deprecated function, "g_basename()".
ashie/gimageview pull request #3
Opened 2019-08-21 06:05 UTC by ikosia

文章を英語で書くのが難しいと感じるので、日本語で書きます。
いくつかのソースコードにおいて、g_basename()が使われていたので、g_path_get_basename()に変更しました。

2019-08-21 06:12 UTC, ashie commented
ありがとうございます！

ただ、`g_basenmae()`の返り値は使用し終えても`g_free()`が必要無いのに対し、`g_path_get_basename()`は`g_free()`が必要です。このままですとメモリリークが発生してしまいます。

* [g-basename](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-basename)
* [g-path-get-basename](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-path-get-basename)

使用し終えた文字列を`g_free()`で解放するように修正して頂くことは可能でしょうか？

2019-08-21 06:13 UTC, ashie commented
> ただ、g_basenmae()の返り値は使用し終えてもg_free()が必要無いのに対し、g_path_get_basename()はg_free()が必要です。このままですとメモリリークが発生してしまいます。

返り値の型に`const`が付いているかいないかで見分けることができます。

2019-08-21 06:24 UTC, ikosia commented
constが付いていなかった意味がやっと分かりました。
ご指摘ありがとうございます。早速修正します。

2019-08-22 06:25 UTC, ikosia commented
`g_free()`を各ソースコードに書き加えました。確認の方よろしくお願いします。

2019-08-22 06:37 UTC, ikosia commented
_P.S._
書き直している時に`g_dirname`が使用されている箇所を見つけました。
一緒に書き直してもよろしいですか?

2019-08-22 06:49 UTC, ashie commented
> 書き直している時に`g_dirname`が使用されている箇所を見つけました。
> 一緒に書き直してもよろしいですか?

1プルリクに対して1トピックでお願いしたいという意味では微妙なところですね。
同種の修正なので1トピックとも言えるのかな。
ということでせっかくなのでお願いします！

2019-08-22 07:15 UTC, ashie requested changes

2019-08-22 07:15 UTC, ashie commented on plugins/thumbnail_view/detailview.c
> +      {
`{`の位置が他と違うと思うので、揃えてほしいです。

2019-08-22 07:15 UTC, ashie commented on src/gimv_dir_view.c
> +      const gchar *bn = g_path_get_basename (path);
`g_path_get_basename()`の返り値の型は`const gchar *`ではなく`gchar *`なので、`const`は付けないで下さい。

変数名は略さないで`basename`とかにしていただけると助かります。
以下も参考にしてみて下さい。

https://www.clear-code.com/blog/2012/6/28.html

2019-08-22 07:15 UTC, ashie commented on plugins/thumbnail_view/detailview.c
> +      return g_strdup (g_path_get_basename (thumb->info->filename));
`g_path_get_basename()`で新規メモリが確保されるので、`g_strdup()`は不要になります。

2019-08-22 07:15 UTC, ashie commented on plugins/thumbnail/xvpics.c
> +   image_name = g_path_get_basename (abspath);
`image_name`は`const`付きで宣言されていますが、`g_path_get_basename()`の返り値の型は`gchar *`で`const`が付かないので、変数宣言の方も`const`を外して下さい。

2019-08-22 07:15 UTC, ashie commented on plugins/thumbnail/xvpics.c
この下の`ERROR`ケースで`image_name`がリークするケースがありそうです。

2019-08-22 07:15 UTC, ashie commented on src/gimv_prefs_win.c
> +      title = g_path_get_basename (_(priv->page->path));
ここの`title`も`const`の件が上記と同様だと思います。以下にも同様のケースがありそうですので同様に修正欲しいです。

2019-08-23 04:43 UTC, ikosia commented
該当する箇所の修正が完了しました。
`plugins/thumbnail/xvpics.c`で気になる部分があったので、issueを立てておきます。

2019-08-23 05:28 UTC, ashie requested changes

2019-08-23 05:28 UTC, ashie commented on plugins/thumbnail/xvpics.c
> +   g_free (image_dir);
単純に`g_free (image_dir)`を追加してしまいますと、`image_dir`が初期化されていない状態のまま`goto`で飛んできて`g_free()`が呼ばれしまうケースがあります。`NULL`で初期化しておいた方が良いかな。

2019-08-23 05:28 UTC, ashie commented on plugins/thumbnail_view/detailview.c
> +      g_free (filename);
`else`のケースでは`g_free()`してはダメです。

2019-08-23 05:28 UTC, ashie commented on src/gimv_thumb_view.c
> +            g_free (basename);
ここは`tmpstr = g_path_get_basename (filename)`で一行で済みますね。

2019-08-23 05:56 UTC, ikosia commented on plugins/thumbnail_view/detailview.c
> +      g_free (filename);
勘違いで変更していました。修正します。

2019-08-23 06:33 UTC, ikosia commented on src/gimv_thumb_view.c
> +            g_free (basename);
見落としていました...修正します。

2019-08-23 07:06 UTC, ashie requested changes

2019-08-23 07:06 UTC, ashie commented on src/utils_gtk.c
>     const gchar *filename_internal
ここにまだ`const`が付いてますね。

2019-08-23 07:21 UTC, ikosia commented on src/utils_gtk.c
>     const gchar *filename_internal
すっかり見落としていました...
修正します。

2019-08-23 07:38 UTC, ikosia commented
不要なconstを見落としていた箇所の修正をしました。
あと、`get_path (const gchar*, const gchar*)`の一部を書き直しました。

2019-08-23 08:02 UTC, merged

2019-08-23 08:02 UTC, ashie commented
マージしました。
ありがとうございます！